const $=s=>document.querySelector(s);let token=sessionStorage.getItem('pe_admin_token')||'';let editing=null;
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function headers(){return {'content-type':'application/json','authorization':`Bearer ${token}`}}
async function showApp(){const r=await fetch('/api/content?admin=1',{headers:{authorization:`Bearer ${token}`}});if(!r.ok){sessionStorage.removeItem('pe_admin_token');token='';return false}$('#login').classList.add('hidden');$('#app').classList.remove('hidden');renderPosts(await r.json());return true}
function renderPosts(data){$('#count').textContent=`${data.length} prompts in your collection`;$('#posts').innerHTML=data.map(p=>`<div class="item"><img class="thumb" src="${p.image}" alt=""><div class="item-main"><strong>${esc(p.title)}</strong><span>${esc(p.category)} · ${esc(p.aspectRatio)}</span></div><div class="actions"><button data-edit="${p.id}">Edit</button><button class="danger" data-delete="${p.id}">Delete</button></div></div>`).join('')||'<p>No posts yet.</p>'}
(async()=>{if(token&&!await showApp())token=''})();
$('#loginBtn').onclick=async()=>{const entered=$('#token').value.trim();if(!entered)return;token=entered;const ok=await showApp();if(ok)sessionStorage.setItem('pe_admin_token',token);else toast('Invalid admin password')};
$('#logout').onclick=()=>{sessionStorage.removeItem('pe_admin_token');token='';location.reload()};$('#refresh').onclick=load;
$('#image').onchange=async e=>{const f=e.target.files[0];if(!f)return;const data=await compress(f);$('#preview').src=data;$('#preview').classList.remove('hidden')};
async function compress(file){return new Promise(resolve=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1400,scale=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.82))};im.src=r.result};r.readAsDataURL(file)})}
async function load(){try{const r=await fetch('/api/content?admin=1',{headers:{authorization:`Bearer ${token}`}});if(r.status===401)throw Error('Invalid admin password');if(!r.ok)throw Error('Unable to load admin data');renderPosts(await r.json())}catch(e){toast(e.message);sessionStorage.removeItem('pe_admin_token');token='';setTimeout(()=>location.reload(),800)}}
document.addEventListener('click',async e=>{const id=e.target.dataset.edit||e.target.dataset.delete;if(!id)return;if(e.target.dataset.edit){const r=await fetch('/api/content?admin=1',{headers:{authorization:`Bearer ${token}`}});if(!r.ok)return toast('Session expired');const data=await r.json();const p=data.find(x=>x.id===id);if(p){editing=p;$('#postId').value=p.id;$('#title').value=p.title;$('#category').value=p.category;$('#ratio').value=p.aspectRatio;$('#style').value=p.aiStyle;$('#difficulty').value=p.difficulty;$('#tags').value=p.tags.join(', ');$('#description').value=p.description;$('#prompt').value=p.prompt;$('#image').required=false;$('#preview').src=p.image;$('#preview').classList.remove('hidden');$('#saveBtn').textContent='Update prompt';$('#cancelBtn').classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}}else{if(confirm('Delete this prompt?')){const r=await fetch('/api/content?id='+encodeURIComponent(id),{method:'DELETE',headers:{authorization:`Bearer ${token}`}});if(r.ok){toast('Deleted');load()}else toast('Delete failed')}}});
$('#cancelBtn').onclick=resetForm;
$('#postForm').onsubmit=async e=>{e.preventDefault();const file=$('#image').files[0];let imageData='';if(file)imageData=await compress(file);else if(!editing)return toast('Please choose an image');const body={id:$('#postId').value||undefined,title:$('#title').value.trim(),category:$('#category').value.trim(),aspectRatio:$('#ratio').value,aiStyle:$('#style').value.trim(),difficulty:$('#difficulty').value, tags:$('#tags').value.split(',').map(x=>x.trim()).filter(Boolean),description:$('#description').value.trim(),prompt:$('#prompt').value.trim(),imageData};const r=await fetch('/api/content',{method:editing?'PUT':'POST',headers:headers(),body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return toast(d.error||'Save failed');toast(editing?'Updated successfully':'Published successfully');resetForm();load()};
function resetForm(){editing=null;$('#postForm').reset();$('#postId').value='';$('#preview').classList.add('hidden');$('#saveBtn').textContent='Publish prompt';$('#cancelBtn').classList.add('hidden');$('#image').required=true}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
