const ADSTERRA_DIRECT_LINK="https://tallytrivial.com/zwr00kyp?key=53c4beb11ca77563d5d82fafb4318b41";
const UNLOCK_DURATION=10000;

const defaultPosts=[
["1","Cinematic Neon Portrait","AI Portrait","9:16","Cinematic","Advanced","A cinematic neon-lit portrait with glossy highlights, atmospheric depth and a premium editorial finish.","portrait, cinematic, neon, realistic","https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85"],
["2","Cyberpunk Street Girl","Cyberpunk","4:5","Cyberpunk","Advanced","A futuristic street scene featuring a confident character under electric signage and rain.","cyberpunk, street, neon, character","https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=85"],
["3","Luxury Fashion Portrait","Fashion","4:5","Editorial","Intermediate","Luxury fashion portrait with controlled studio light, rich texture and magazine-grade composition.","fashion, luxury, editorial, portrait","https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=85"],
["4","Dark Fantasy Warrior","Fantasy","4:5","Dark Fantasy","Advanced","A dramatic fantasy warrior in an ancient environment with cinematic fog and detailed armor.","fantasy, warrior, dark, cinematic","https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=900&q=85"],
["5","Futuristic Dubai","Architecture","16:9","Futuristic","Intermediate","A visionary futuristic city skyline inspired by luxury architecture and glowing night streets.","dubai, architecture, futuristic, city","https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=85"],
["6","AI Product Advertisement","Product Ads","1:1","Commercial","Intermediate","A premium product advertisement with clean reflections, controlled lighting and a bold visual hierarchy.","product, commercial, advertisement, studio","https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85"],
["7","Fantasy Queen","Fantasy","4:5","Fantasy","Advanced","A regal fantasy queen surrounded by soft atmospheric light, ornate costume details and cinematic depth.","queen, fantasy, character, portrait","https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=85"],
["8","Rainy Tokyo Street","Photography","16:9","Cinematic","Intermediate","A moody rainy urban street filled with reflections, soft neon and documentary-style atmosphere.","tokyo, rain, street, cinematic","https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1200&q=85"],
["9","Ultra Realistic Male Portrait","AI Portrait","4:5","Photorealistic","Advanced","An ultra-realistic close portrait with natural skin texture, controlled contrast and subtle film grain.","male, portrait, realistic, photography","https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=85"],
["10","Futuristic Space Station","Sci-Fi","16:9","Sci-Fi","Advanced","A vast orbital station with glowing corridors, monumental scale and cinematic science-fiction lighting.","space, station, sci-fi, futuristic","https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1200&q=85"],
["11","Dreamy Nature Landscape","Nature","16:9","Dreamy","Beginner","A tranquil dreamlike landscape with soft morning haze, layered mountains and painterly light.","nature, landscape, dreamy, mountains","https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85"],
["12","Luxury Car Cinematic Shot","Photography","16:9","Automotive","Advanced","A luxury car photographed like a film still, with dramatic reflections and a premium night setting.","car, luxury, cinematic, automotive","https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85"]
].map(x=>({id:x[0],title:x[1],category:x[2],aspectRatio:x[3],aiStyle:x[4],difficulty:x[5],description:x[6],tags:x[7].split(", "),image:x[8],prompt:`${x[6]} Ultra-detailed composition, professional lighting, realistic materials and textures, cinematic color grading, strong focal point, subtle atmospheric depth, high-end visual storytelling, carefully balanced framing, crisp details, premium finish. Keywords: ${x[7]}.`}));

let posts=[...defaultPosts];
const categories=["AI Portrait","Cinematic","Fantasy","Anime","Fashion","Photography","Architecture","Nature","Cyberpunk","Product Ads","3D Art","Digital Art","Character Design","Horror","Sci-Fi"];
let currentFilter=""; let currentPost=null; let timer=null;
const $=s=>document.querySelector(s);
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function card(p){return `<article class="card"><div class="card-img" style="background-image:url('${p.image}')"></div><div class="card-body"><h3 class="card-title">${p.title}</h3><div class="chips"><span class="chip">${p.category}</span><span class="chip">${p.aiStyle}</span></div><div class="card-bottom"><span class="ratio">${p.aspectRatio}</span><button class="view-btn" data-id="${p.id}">View Prompt →</button></div></div></article>`}
function renderGallery(list=posts){$("#gallery").innerHTML=list.map(card).join("");$("#emptyState").classList.toggle("hidden",!!list.length);$("#activeFilter").textContent=currentFilter||"All images"}
function mini(p){return `<article class="mini" data-id="${p.id}"><div class="mini-img" style="background-image:url('${p.image}')"></div><div><h3>${p.title}</h3><p>${p.category} · ${p.aspectRatio}</p></div></article>`}
function renderExtras(){ $("#categoriesGrid").innerHTML=categories.map(c=>`<button class="cat" data-cat="${c}">${c}</button>`).join("");$("#trendingGrid").innerHTML=posts.slice(0,4).map(mini).join("");$("#latestGrid").innerHTML=posts.slice().reverse().slice(0,4).map(mini).join("")}
async function getPrompt(id){const r=await fetch(`/api/content?prompt=${encodeURIComponent(id)}`,{cache:"no-store"});if(!r.ok)throw new Error("Prompt unavailable");return (await r.json()).prompt}
function openPost(id){currentPost=posts.find(p=>p.id===id);if(!currentPost)return;$("#postImage").style.backgroundImage=`url('${currentPost.image}')`;$("#postCategory").textContent=currentPost.category;$("#postRatio").textContent=currentPost.aspectRatio;$("#postStyle").textContent=currentPost.aiStyle;$("#postDifficulty").textContent=currentPost.difficulty;$("#postTitle").textContent=currentPost.title;$("#postDescription").textContent=currentPost.description;resetUnlock();$("#modal").classList.remove("hidden");$("#modal").setAttribute("aria-hidden","false");document.body.style.overflow="hidden";restoreUnlock()}
function closeModal(){$("#modal").classList.add("hidden");document.body.style.overflow="";if(timer)clearInterval(timer)}
function key(id){return "promptEraUnlock_"+id}
function resetUnlock(){if(timer)clearInterval(timer);$("#unlockBox").classList.remove("hidden");$("#timerBox").classList.add("hidden");$("#promptBox").classList.add("hidden")}
function startUnlock(){if(!ADSTERRA_DIRECT_LINK){toast("Advertising link is not configured yet.");return}const state={startedAt:Date.now(),unlocked:false};localStorage.setItem(key(currentPost.id),JSON.stringify(state));window.open(ADSTERRA_DIRECT_LINK,"_blank","noopener,noreferrer");showTimer(state.startedAt)}
async function showTimer(startedAt){$("#unlockBox").classList.add("hidden");$("#timerBox").classList.remove("hidden");if(timer)clearInterval(timer);const tick=async()=>{const elapsed=Date.now()-startedAt;const left=Math.max(0,UNLOCK_DURATION-elapsed);const sec=Math.ceil(left/1000);$("#timerValue").textContent=sec;$("#timerText").textContent=left>0?`Please wait ${sec} more second${sec===1?"":"s"} to unlock this prompt.`:"Prompt unlocked.";$("#timerBox .timer-ring").style.setProperty("--progress",`${Math.min(100,elapsed/UNLOCK_DURATION*100)}%`);if(left<=0){clearInterval(timer);try{const prompt=await getPrompt(currentPost.id);currentPost.prompt=prompt;localStorage.setItem(key(currentPost.id),JSON.stringify({startedAt,unlocked:true}));unlockPrompt()}catch{toast("Could not load prompt. Please try again.")}}};tick();timer=setInterval(tick,250)}
function unlockPrompt(){$("#timerBox").classList.add("hidden");$("#promptBox").classList.remove("hidden");$("#promptText").textContent=currentPost.prompt}
function restoreUnlock(){const raw=localStorage.getItem(key(currentPost.id));if(!raw)return;try{const s=JSON.parse(raw);if(s.unlocked){getPrompt(currentPost.id).then(p=>{currentPost.prompt=p;unlockPrompt()}).catch(()=>{});}else if(Date.now()-s.startedAt>=UNLOCK_DURATION){getPrompt(currentPost.id).then(p=>{currentPost.prompt=p;localStorage.setItem(key(currentPost.id),JSON.stringify({startedAt:s.startedAt,unlocked:true}));unlockPrompt()}).catch(()=>{});}else showTimer(s.startedAt)}catch{}}
function filter(){const q=$("#searchInput").value.trim().toLowerCase();const list=posts.filter(p=>(!currentFilter||p.category===currentFilter)&&(!q||[p.title,p.category,p.aiStyle,p.description,...p.tags].join(" ").toLowerCase().includes(q)));renderGallery(list)}
function share(type){const url=encodeURIComponent(location.href);const text=encodeURIComponent(currentPost?.title||"Prompt Era AI Prompt");const urls={facebook:`https://www.facebook.com/sharer/sharer.php?u=${url}`,x:`https://twitter.com/intent/tweet?text=${text}&url=${url}`,whatsapp:`https://wa.me/?text=${text}%20${url}`,telegram:`https://t.me/share/url?url=${url}&text=${text}`};if(urls[type])window.open(urls[type],"_blank","noopener,noreferrer")}

document.addEventListener("click",e=>{const id=e.target.closest("[data-id]")?.dataset.id;if(id)openPost(id);const cat=e.target.closest("[data-cat]")?.dataset.cat;if(cat){currentFilter=currentFilter===cat?"":cat;filter();location.hash="images"}if(e.target.matches("[data-close]"))closeModal();if(e.target.dataset.share)share(e.target.dataset.share)});
$("#unlockBtn").onclick=startUnlock;
$("#copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText($("#promptText").textContent);$("#copyBtn").textContent="Copied ✓";toast("Prompt copied");setTimeout(()=>$("#copyBtn").textContent="Copy Prompt",1600)}catch{$("#copyBtn").textContent="Select & Copy";toast("Unable to copy automatically. Please select and copy manually.")}};
$("#copyLink").onclick=async()=>{try{await navigator.clipboard.writeText(location.href);toast("Link copied")}catch{toast("Copy failed")}};
$("#searchInput").oninput=filter;
$("#searchToggle").onclick=()=>{$("#searchPanel").classList.toggle("open");if($("#searchPanel").classList.contains("open"))$("#searchInput").focus()};
$("#menuToggle").onclick=()=>$("#mobileNav").classList.toggle("open");
window.addEventListener("hashchange",()=>{const id=location.hash.slice(1);const p=posts.find(x=>x.id===id);if(p)openPost(p.id)});
async function loadRemote(){try{const r=await fetch('/api/content',{cache:'no-store'});if(!r.ok)return;const remote=await r.json();if(Array.isArray(remote)&&remote.length){const map=new Map(remote.map(p=>[p.id,p]));posts=[...defaultPosts.filter(p=>!map.has(p.id)),...remote];renderGallery();renderExtras();}}catch(e){console.warn('Remote content unavailable',e)}}
renderGallery();renderExtras();loadRemote();
